---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: ^3rd-party|COPYING|.gitmodules|conan
default_language_version:
  python: python3
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=150]
      - id: check-ast
      - id: check-byte-order-marker
        exclude: ^.*(\.cs|\.vb|\.cbproj|\.groupproj|\.props|\.sln|\.vcxproj|\.vcxproj.filters)$
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
        exclude: >
          (?x)(
           ^\.vscode/.*\.json|
           ^\.github/.*\.yml
           )$
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
        exclude: ^.*(\.cs|\.vb|\.cbproj|\.groupproj|\.props|\.sln|\.vcxproj|\.vcxproj.filters)$
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: file-contents-sorter
      - id: fix-byte-order-marker
        exclude: ^.*(\.cs|\.vb\\.cbproj|\.groupproj|\.props|\.sln|\.vcxproj|\.vcxproj.filters)$
      - id: fix-encoding-pragma
      - id: forbid-new-submodules
      - id: forbid-submodules
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: name-tests-test
      - id: no-commit-to-branch
        args: [--branch, gh-pages]
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
        exclude: ^.*(\.cs|\.vb\\.cbproj|\.groupproj|\.props|\.sln|\.vcxproj|\.vcxproj.filters)$
        args: [--markdown-linebreak-ext=md]
        stages:
          - commit
          - manual
          
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0 # Use the ref you want to point at
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.1
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==21.7b0]

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: bundler-audit
      - id: check-mailmap
      - id: fasterer
      - id: forbid-binary
        exclude: >
          (?x)^(
            .+\.bmp|
            .+\.BMP|
            .+\.png|
            .+\.pdf|
            .+\.woff|
            .+\.woff2|
            .+\.tff|
            .+\.ico|
            .+\.icns|
            .+\.svgz|
            .+\.ttf
          )$
      - id: git-check # Configure in .gitattributes
      - id: git-dirty # Configure in .gitignore
      - id: reek
      - id: rubocop
      - id: script-must-not-have-extension
        name: Local policy is to exclude extension from all shell files
        types: [shell]
      - id: script-must-not-have-extension
        name: Executable Ruby scripts must not have a file extension
        types: [ruby, executable]
      - id: shellcheck
        args: ['--color=always', '--shell=bash', '-x', '-a', '--exclude=SC1090']
      - id: shfmt

  - repo: https://github.com/Lucas-C/pre-commit-hooks-java
    rev: 1.3.10
    hooks:
      - id: validate-html

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: remove-crlf
      - id: forbid-crlf
      - id: remove-tabs
      - id: forbid-tabs

  - repo: https://github.com/Lucas-C/pre-commit-hooks-java
    rev: 1.3.10
    hooks:
      - id: validate-html

  - repo: https://github.com/Lucas-C/pre-commit-hooks-lxml
    rev: v1.1.0
    hooks:
      - id: forbid-html-img-without-alt-text
      - id: forbid-non-std-html-attributes
      - id: detect-missing-css-classes
        args:
          - --css-files-dir
          - .
          - --html-files-dir
          - .
      - id: html-tags-blacklist
      - id: html-attributes-blacklist

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.2
    hooks:
      - id: python-safety-dependencies-check

  - repo: https://github.com/jstewmon/check-swagger
    rev: v0.1.4
    hooks:
      - id: check-swagger

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3 # or higher tag
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]

  - repo: https://github.com/noahsark769/xcodeproj-sort-pre-commit-hook
    rev: v1.1.0
    hooks:
      - id: xcodeproj-sort
        args: [--groups-position=above]

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint
        stages: [commit-msg]

  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black

  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.1
    hooks:
      - id: docker-compose-check

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        exclude: ^.*(\.ts|\.xib|\.wxs)$
        name: prettier + plugin-xml
        additional_dependencies:
          - prettier@2.3.2
          - '@prettier/plugin-ruby@'
          - '@prettier/plugin-xml@0.12.0'
        args:
          - --write
          - --list-different
          - --ignore-unknown
          - --plugin=@prettier/plugin-ruby
          - --prose-wrap=always
          - --print-width=88

  - repo: https://github.com/milin/giticket
    rev: v1.3
    hooks:
      - id: giticket
        args: ['--regex=PROJ-[0-9]', '--format={ticket} {commit_msg}'] # Optional

  - repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.11.0
    hooks:
      - id: check-autopkg-recipe-list
      - id: check-autopkg-recipes
      - id: check-git-config-email
      - id: check-jamf-extension-attributes
      - id: check-jamf-scripts
      - id: check-jamf-profiles
      - id: check-munki-pkgsinfo
      - id: check-munkiadmin-scripts
      - id: check-munkipkg-buildinfo
      - id: check-outset-scripts
      - id: check-plists
      - id: forbid-autopkg-overrides
      - id: forbid-autopkg-trust-info

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.4
    hooks:
      - id: clang-format
      - id: clang-tidy
      - id: oclint
        args: [-enable-clang-static-analyzer, -enable-global-analysis]
      - id: uncrustify

  - repo: https://gitlab.com/daverona/pre-commit/cpp
    rev: 0.8.0
    hooks:
      - id: cppcheck # static analyzer for C/C++ code

  - repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: check-poetry

  - repo: https://github.com/APIDevTools/swagger-cli
    rev: v4.0.4
    hooks:
      - id: swagger-validation
