name: Changelog Validate

on: [pull_request]

jobs:
    changelog:
        runs-on: ubuntu-latest
        name: Changelog Validate
        steps:
            - uses: actions/checkout@v2
            - uses: zattoo/changelog@v1
              with:
                  token: ${{github.token}}
                  sources:
                      "/"
